# Generated by Django 6.0.3 on 2026-04-11 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('content', models.TextField(null=True)),
                ('category_id', models.UUIDField(null=True)),
                ('created_by', models.UUIDField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Level 2'), ('PENDING_L3', 'Pending Level 3'), ('PENDING_L4', 'Pending Level 4'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
