# Generated by Django 6.0.3 on 2026-04-12 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_head_user_id'),
        ('reports', '0002_alter_report_content_alter_report_created_by'),
        ('users', '0002_user_avatar_url_user_department_id_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='current_approval_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='department_id',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='departments.department'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='idx_reports_status'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by'], name='idx_reports_created_by'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['department_id', 'status'], name='idx_reports_department'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='idx_reports_created_at'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='report_id',
            field=models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='upload_by',
            field=models.ForeignKey(blank=True, db_column='upload_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='reportattachment',
            index=models.Index(fields=['report_id'], name='idx_attachments_report'),
        ),
    ]
