# Generated by Django 6.0.3 on 2026-04-12 10:48

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportattachment_report_current_approval_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_attachment_upload_to),
        ),
    ]
