# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_reportattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
