# Generated by Django 5.2.14 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING_L2', '2-daraja tasdiqlash kutilmoqda'), ('PENDING_L3', '3-daraja tasdiqlash kutilmoqda'), ('PENDING_L4', '4-daraja tasdiqlash kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('REVISION', "Qayta ko'rib chiqish"), ('ARCHIVED', 'Arxivlangan')], default='DRAFT', max_length=20),
        ),
    ]
