# Generated by Django 6.0.3 on 2026-04-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_user_id',
            field=models.ForeignKey(blank=True, db_column='head_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='users.user'),
        ),
    ]
