# Generated by Django 5.2.14 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivelog',
            name='status',
            field=models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz')], max_length=20),
        ),
    ]
