# Generated by Django 6.0.3 on 2026-04-12 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0003_reportattachment_report_current_approval_level_and_more'),
        ('users', '0002_user_avatar_url_user_department_id_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_REVISION', 'Request Revision'), ('ARCHIVE', 'Archive')], max_length=20)),
                ('comment', models.TextField()),
                ('previous_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Level 2'), ('PENDING_L3', 'Pending Level 3'), ('PENDING_L4', 'Pending Level 4'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Level 2'), ('PENDING_L3', 'Pending Level 3'), ('PENDING_L4', 'Pending Level 4'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_id', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='users.user')),
                ('report_id', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='reports.report')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_id', '-created_at'], name='idx_approval_report')],
            },
        ),
    ]
