# Generated by Django 5.2.14 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Yuborish'), ('APPROVE', 'Tasdiqlash'), ('REJECT', 'Rad etish'), ('REQUEST_REVISION', "Qayta ko'rib chiqishni so'rash"), ('ARCHIVE', 'Arxivlash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='new_status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING_L2', '2-daraja tasdiqlash kutilmoqda'), ('PENDING_L3', '3-daraja tasdiqlash kutilmoqda'), ('PENDING_L4', '4-daraja tasdiqlash kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('REVISION', "Qayta ko'rib chiqish"), ('ARCHIVED', 'Arxivlangan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='previous_status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING_L2', '2-daraja tasdiqlash kutilmoqda'), ('PENDING_L3', '3-daraja tasdiqlash kutilmoqda'), ('PENDING_L4', '4-daraja tasdiqlash kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('REVISION', "Qayta ko'rib chiqish"), ('ARCHIVED', 'Arxivlangan')], max_length=20),
        ),
    ]
