export const state = {
  apiBase: "",
  language: window.localStorage.getItem("hrmm_language") || "uz",
  themeId: window.localStorage.getItem("hrmm_theme_id") || window.localStorage.getItem("hrmm_theme") || "classic-dark",
  themeMode: window.localStorage.getItem("hrmm_theme_mode") || "single",
  increaseContrast: window.localStorage.getItem("hrmm_increase_contrast") === "true",
  bgEffect: window.localStorage.getItem("hrmm_bg_effect") || "none",
  accessToken: "",
  refreshToken: "",
  currentUser: null,
  pendingChallengeToken: "",
  pendingEmailChallengeId: "",
  pendingLoginUser: null,
  pendingVerificationMethod: "",
  twoFactorSetup: null,
  departments: [],
  units: [],
  users: [],
  reports: [],
  leaves: [],
  auditLogs: [],
  archiveLogs: [],
  notifications: [],
  adminDashboard: null,
  analyticsDashboard: null,
  leaveCalendar: [],
  reportHistory: [],
  reviewHistory: [],
  lastCreatedReportId: "",
  pendingApprovals: [],
  homeActivityFilter: "all",
  feedbackEntries: [],
};
