# Generated by Django 6.0.3 on 2026-04-11 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('SPECIALIST', 'Specialist'), ('UNIT_HEAD', 'Unit Head'), ('DEPT_HEAD', 'Department Head'), ('DIRECTOR', 'Director')], max_length=20)),
                ('department_id', models.UUIDField(null=True)),
                ('unit_id', models.UUIDField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('avatar_url', models.CharField(max_length=500, null=True)),
                ('last_login_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
