# Generated by Django 5.2.14 on 2026-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotpchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpchallenge',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Kirish')], default='LOGIN', max_length=30),
        ),
    ]
