# Generated by Django 6.0.7 on 2026-07-11 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emailotpchallenge_purpose'),
        ('users', '0012_alter_user_job_level_alter_user_job_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRLoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Rad etildi'), ('EXPIRED', 'Muddati tugagan')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_qr_login_challenges', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_login_challenges', to='users.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
