# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_url_user_department_id_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_level",
            field=models.CharField(
                blank=True,
                choices=[("JUNIOR", "Junior"), ("MIDDLE", "Middle"), ("SENIOR", "Senior")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEVOPS", "DevOps"),
                    ("IT_ENGINEER", "IT Engineer"),
                    ("ANDROID_DEV", "Android Developer"),
                    ("BACKEND_DEV", "Backend Developer"),
                    ("FRONTEND_DEV", "Frontend Developer"),
                    ("MANAGER", "Manager"),
                    ("DIRECTOR", "Director"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
