# Generated by Django 5.2.14 on 2026-05-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_seed_default_departments'),
        ('units', '0003_seed_default_units'),
        ('users', '0006_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='uz', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department_id',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_users', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_level',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SPECIALIST', 'Specialist'), ('UNIT_HEAD', 'Unit Head'), ('DEPT_HEAD', 'Department Head'), ('DIRECTOR', 'Director')], default='SPECIALIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_users', to='units.unit'),
        ),
    ]
