# Generated by Django 5.2.14 on 2026-06-29 07:35

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_force_repair_role_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_level',
            field=models.CharField(blank=True, choices=[('JUNIOR', "Boshlang'ich (Junior)"), ('MIDDLE', "O'rta (Middle)"), ('SENIOR', 'Yuqori (Senior)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_role',
            field=models.CharField(blank=True, choices=[('DEVOPS', 'DevOps muhandisi'), ('IT_ENGINEER', 'IT muhandisi'), ('ANDROID_DEV', 'Android dasturchi'), ('BACKEND_DEV', 'Backend dasturchi'), ('FRONTEND_DEV', 'Frontend dasturchi'), ('MANAGER', 'Menejer'), ('DIRECTOR', 'Direktor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha'), ('tr', 'Turkcha')], default='uz', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SPECIALIST', 'Mutaxassis'), ('UNIT_HEAD', "Bo'linma rahbari"), ('DEPT_HEAD', "Bo'lim boshlig'i"), ('DIRECTOR', 'Direktor')], default='SPECIALIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=apps.users.models.TOTPEncryptedField(blank=True, max_length=256, null=True),
        ),
    ]
