(function () {
  const shared = {
    radiusSm: "6px",
    radiusMd: "8px",
    radiusLg: "12px",
    radiusXl: "16px",
    iconBtnSize: "36px",
  };

  const themes = [
    {
      id: "classic-light",
      name: "Classic Light",
      description: "Crisp light workspace with dark text and verified contrast.",
      mode: "light",
      badge: "",
      tokens: {
        ...shared,
        background: "#f8fafc",
        backgroundDeep: "#eef2f7",
        backgroundElevated: "#ffffff",
        surface: "#ffffff",
        surfaceElevated: "#ffffff",
        border: "#d6dee8",
        borderStrong: "#aab8c8",
        textPrimary: "#0f172a",
        textSecondary: "#334155",
        textMuted: "#5f6f85",
        accent: "#1f6feb",
        accentHover: "#185abc",
        accentSoft: "#dbeafe",
        success: "#087f5b",
        warning: "#9a6700",
        danger: "#cf222e",
      },
      contrastTokens: {
        background: "#ffffff",
        backgroundDeep: "#f1f5f9",
        textSecondary: "#1e293b",
        textMuted: "#334155",
        border: "#94a3b8",
        accent: "#0757c2",
        accentHover: "#003f91",
      },
    },
    {
      id: "classic-dark",
      name: "Classic Dark",
      description: "GitHub-inspired dark canvas with high-clarity text.",
      mode: "dark",
      badge: "",
      tokens: {
        ...shared,
        background: "#0d1117",
        backgroundDeep: "#010409",
        backgroundElevated: "#161b22",
        surface: "#161b22",
        surfaceElevated: "#21262d",
        border: "#30363d",
        borderStrong: "#8b949e",
        textPrimary: "#f0f6fc",
        textSecondary: "#c9d1d9",
        textMuted: "#8b949e",
        accent: "#58a6ff",
        accentHover: "#79c0ff",
        accentSoft: "rgba(88, 166, 255, 0.18)",
        success: "#3fb950",
        warning: "#d29922",
        danger: "#f85149",
      },
      contrastTokens: {
        background: "#010409",
        backgroundDeep: "#000000",
        textSecondary: "#f0f6fc",
        textMuted: "#d0d7de",
        border: "#8b949e",
        accent: "#79c0ff",
        accentHover: "#a5d6ff",
      },
    },
    {
      id: "soft-dark",
      name: "Soft Dark",
      description: "Lower-glare dark theme for long review sessions.",
      mode: "dark",
      badge: "New",
      tokens: {
        ...shared,
        background: "#171923",
        backgroundDeep: "#11131b",
        backgroundElevated: "#202331",
        surface: "#202331",
        surfaceElevated: "#292d3d",
        border: "#3a4054",
        borderStrong: "#697089",
        textPrimary: "#edf2f7",
        textSecondary: "#cbd5e1",
        textMuted: "#9aa6b8",
        accent: "#7dd3fc",
        accentHover: "#bae6fd",
        accentSoft: "rgba(125, 211, 252, 0.16)",
        success: "#6ee7b7",
        warning: "#facc15",
        danger: "#fca5a5",
      },
      contrastTokens: {
        background: "#0f1118",
        backgroundDeep: "#080a10",
        textSecondary: "#f8fafc",
        textMuted: "#dbe4ef",
        border: "#9aa6b8",
        accent: "#bae6fd",
        accentHover: "#e0f2fe",
      },
    },
    {
      id: "soft-light",
      name: "Soft Light",
      description: "Warmer light surfaces with a calmer HR dashboard feel.",
      mode: "light",
      badge: "",
      tokens: {
        ...shared,
        background: "#fbfaf7",
        backgroundDeep: "#f2efe8",
        backgroundElevated: "#fffdf8",
        surface: "#fffdf8",
        surfaceElevated: "#ffffff",
        border: "#d8d0c4",
        borderStrong: "#a99f91",
        textPrimary: "#1f2933",
        textSecondary: "#40505f",
        textMuted: "#667585",
        accent: "#0f766e",
        accentHover: "#0b5f59",
        accentSoft: "#dff7f3",
        success: "#087f5b",
        warning: "#936400",
        danger: "#b42318",
      },
      contrastTokens: {
        background: "#fffefa",
        backgroundDeep: "#f4efe5",
        textSecondary: "#243443",
        textMuted: "#3d4f60",
        border: "#8b8174",
        accent: "#075e57",
        accentHover: "#034c47",
      },
    },
    {
      id: "clear-spectrum",
      name: "Clear Spectrum",
      description: "Colorblind-friendly accents with strong status separation.",
      mode: "light",
      badge: "Beta",
      tokens: {
        ...shared,
        background: "#f7f9fb",
        backgroundDeep: "#e9eef5",
        backgroundElevated: "#ffffff",
        surface: "#ffffff",
        surfaceElevated: "#ffffff",
        border: "#cbd5e1",
        borderStrong: "#8796a9",
        textPrimary: "#111827",
        textSecondary: "#374151",
        textMuted: "#5b6778",
        accent: "#005fcc",
        accentHover: "#004799",
        accentSoft: "#dbeafe",
        success: "#00875a",
        warning: "#b35c00",
        danger: "#c4002f",
      },
      contrastTokens: {
        background: "#ffffff",
        backgroundDeep: "#edf2f7",
        textSecondary: "#1f2937",
        textMuted: "#374151",
        border: "#7b8794",
        accent: "#004799",
        accentHover: "#003366",
      },
    },
    {
      id: "ikki-ton",
      name: "Ikki Ton",
      description: "Yangi dual-tone palitra: och havodor fon, to'q indigo sidebar va indigo→teal gradient.",
      mode: "light",
      badge: "New",
      tokens: {
        ...shared,
        background: "#eef1f6",
        backgroundDeep: "#e4e8f0",
        backgroundElevated: "#f4f6fb",
        surface: "#ffffff",
        surfaceElevated: "#ffffff",
        rail: "#171a2e",
        border: "rgba(163, 171, 194, 0.35)",
        borderStrong: "#7c86a0",
        textPrimary: "#1d2333",
        textSecondary: "#4a5268",
        textMuted: "#7c86a0",
        accent: "#5b6cff",
        accentHover: "#2dd4bf",
        accentSoft: "rgba(91, 108, 255, 0.14)",
        success: "#0d9488",
        warning: "#b06f24",
        danger: "#b4483a",
      },
      contrastTokens: {
        background: "#ffffff",
        backgroundDeep: "#eef1f6",
        backgroundElevated: "#f4f6fb",
        rail: "#0b0d1a",
        border: "#7c86a0",
        borderStrong: "#4a5268",
        textSecondary: "#1d2333",
        textMuted: "#4a5268",
        accent: "#3d4ff5",
        accentHover: "#0d9488",
      },
    },
  ];

  window.HRMM_THEME_OPTIONS = themes;
})();
