# Generated by Django 5.2.14 on 2026-05-11 07:52

import uuid
from django.db import migrations, models


def populate_leave_numbers(apps, schema_editor):
    LeaveRequest = apps.get_model('leave_management', 'LeaveRequest')
    for index, leave in enumerate(LeaveRequest.objects.all().order_by('created_at'), start=1):
        leave.leave_number = index
        leave.save(update_fields=['leave_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leaverequest_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_leave_numbers, migrations.RunPython.noop),
    ]
