# Generated by Django 5.2.14 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_leaverequest_leave_number_alter_leaverequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', "Yillik ta'til"), ('SICK', "Kasallik ta'tili"), ('UNPAID', "To'lovsiz ta'til"), ('MATERNITY', "Tug'ruq ta'tili"), ('OTHER', 'Boshqa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=20),
        ),
    ]
