from django.urls import path ,include
from .views import (
    HRMMTokenRefreshView,
    LoginView,
    LogoutView,
    MeView,
    PasswordChangeView,
    QRLoginApproveView,
    QRLoginChallengeView,
    QRLoginCompleteView,
    QRLoginStatusView,
    RegisterView,
    TwoFactorDisableView,
    TwoFactorSetupView,
    TwoFactorVerifySetupView,
    VerifyLoginEmailOTPView,
    VerifyLoginTwoFactorView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("login/verify-email-otp/", VerifyLoginEmailOTPView.as_view(), name="login_verify_email_otp"),
    path("login/verify-2fa/", VerifyLoginTwoFactorView.as_view(), name="login_verify_2fa"),
    path("login/qr-challenge/", QRLoginChallengeView.as_view(), name="login_qr_challenge"),
    path("login/qr-status/", QRLoginStatusView.as_view(), name="login_qr_status"),
    path("login/qr-approve/", QRLoginApproveView.as_view(), name="login_qr_approve"),
    path("login/qr-complete/", QRLoginCompleteView.as_view(), name="login_qr_complete"),
    path("refresh/", HRMMTokenRefreshView.as_view(), name="token_refresh"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("me/", MeView.as_view(), name="me"),
    path("password/", PasswordChangeView.as_view(), name="password_change"),
    path("two-factor/setup/", TwoFactorSetupView.as_view(), name="two_factor_setup"),
    path("two-factor/verify/", TwoFactorVerifySetupView.as_view(), name="two_factor_verify"),
    path("two-factor/disable/", TwoFactorDisableView.as_view(), name="two_factor_disable"),
]
