# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations
from django.utils import timezone


def seed_default_units(apps, schema_editor):
    Department = apps.get_model("departments", "Department")
    Unit = apps.get_model("units", "Unit")

    # Keep the migration idempotent: if units already exist, don't duplicate them.
    if Unit.objects.exists():
        return

    departments = Department.objects.all()
    if not departments.exists():
        return

    for dep in departments:
        # One unit per department by default.
        Unit.objects.create(
            department_id=dep,
            name=dep.name,
            code=dep.code,
            head_user_id=None,
            is_active=True,
            created_at=timezone.now(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0002_alter_unit_department_id_alter_unit_head_user_id"),
    ]

    operations = [
        migrations.RunPython(seed_default_units, migrations.RunPython.noop),
    ]

