# Generated by Codex on 2026-04-13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_user_job_level_user_job_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("type", models.CharField(choices=[("APPROVAL", "Approval"), ("REJECTION", "Rejection"), ("INFO", "Info"), ("REMINDER", "Reminder")], max_length=20)),
                ("reference_type", models.CharField(blank=True, max_length=50, null=True)),
                ("reference_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="users.user")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user_id", "is_read", "-created_at"], name="idx_notifications_user"),
        ),
    ]
