# Generated by Django 5.2.14 on 2026-05-11 07:52

import uuid
from django.db import migrations, models


def populate_notification_numbers(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for index, notification in enumerate(Notification.objects.all().order_by('created_at'), start=1):
        notification.notification_number = index
        notification.save(update_fields=['notification_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_notification_numbers, migrations.RunPython.noop),
    ]
