# Generated by Django 5.2.14 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_review_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPROVAL', 'Tasdiqlash'), ('REJECTION', 'Rad etish'), ('INFO', "Ma'lumot"), ('REMINDER', 'Eslatma')], max_length=20),
        ),
    ]
